# Translation of Odoo Server.
# This file contains the translation of the following modules:
# * account_invoice_constraint_chronology
#
# Translators:
# OCA Transbot <transbot@odoo-community.org>, 2018
# Quentin THEURET <odoo@kerpeo.com>, 2018
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 11.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-01-30 16:31+0000\n"
"PO-Revision-Date: 2024-05-27 13:33+0200\n"
"Last-Translator: Rémi <remi@le-filament.com>\n"
"Language-Team: French (https://www.transifex.com/oca/teams/23907/fr/)\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n > 1;\n"
"X-Generator: Poedit 3.4.2\n"

#. module: account_invoice_constraint_chronology
#: model:ir.model.fields,field_description:account_invoice_constraint_chronology.field_account_journal__check_chronology
msgid "Check Chronology"
msgstr "Vérifier la chronologie"

#. module: account_invoice_constraint_chronology
#. odoo-python
#: code:addons/account_invoice_constraint_chronology/model/account_move.py:0
#, python-format
msgid ""
"Chronology conflict: A conflicting draft invoice dated before {date_invoice} "
"exists, please validate it first."
msgstr ""
"Conflit de chronologie : Il existe une facture brouillon portant une date "
"antérieur au {date_invoice}, veuillez d'abord valider la facture brouillon "
"antérieur à celle-ci."

#. module: account_invoice_constraint_chronology
#. odoo-python
#: code:addons/account_invoice_constraint_chronology/model/account_move.py:0
#, python-format
msgid ""
"Chronology conflict: A conflicting validated invoice dated after "
"{date_invoice} exists."
msgstr ""
"Conflit de chronologie : Il existe une ou des facture(s) validée(s) datée(s) "
"après {date_invoice}. La date de cette facture doit être postérieur à la "
"dernière facture."

#. module: account_invoice_constraint_chronology
#. odoo-python
#: code:addons/account_invoice_constraint_chronology/model/account_move.py:0
#, python-format
msgid ""
"Chronology conflict: An invoice with a higher number {highest_name} dated "
"before {date_invoice} exists."
msgstr ""
"Conflit de chronologie : Une facture portant un numéro supérieur "
"{highest_name} et datée avant {date_invoice} existe."

#. module: account_invoice_constraint_chronology
#. odoo-python
#: code:addons/account_invoice_constraint_chronology/model/account_move.py:0
#, python-format
msgid ""
"Chronology conflict: Invoice {name} cannot be {time} invoice {inv_name}."
msgstr ""
"Conflit de chronologie : La facture {name} ne peut pas être validé à la date "
"du {time} de la facture {inv_name}."

#. module: account_invoice_constraint_chronology
#: model:ir.model,name:account_invoice_constraint_chronology.model_account_journal
msgid "Journal"
msgstr "Journal"

#. module: account_invoice_constraint_chronology
#: model:ir.model,name:account_invoice_constraint_chronology.model_account_move
msgid "Journal Entry"
msgstr "Ecriture Comptable"

#, python-format
#~ msgid ""
#~ "Chronology Error. Please confirm older draft invoices before "
#~ "{date_invoice} and try again."
#~ msgstr ""
#~ "Erreur de chronologie. Veuillez confirmer les anciennes factures en "
#~ "brouillon datées d'avant le {date_invoice} et réessayer."

#, python-format
#~ msgid ""
#~ "Chronology Error. There exist at least one invoice with a later date to "
#~ "{date_invoice}."
#~ msgstr ""
#~ "Erreur de chronologie. Il existe au moins une facture avec une date "
#~ "ultérieure au {date_invoice}."

#~ msgid "Invoice"
#~ msgstr "Facture"
