# Translation of Odoo Server.
# This file contains the translation of the following modules:
# * account_invoice_constraint_chronology
#
# Translators:
# OCA Transbot <transbot@odoo-community.org>, 2018
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 11.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-01-30 16:31+0000\n"
"PO-Revision-Date: 2023-01-04 00:59+0000\n"
"Last-Translator: Bole <bole@dajmi5.com>\n"
"Language-Team: Croatian (https://www.transifex.com/oca/teams/23907/hr/)\n"
"Language: hr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Plural-Forms: nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n"
"%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;\n"
"X-Generator: Weblate 4.14.1\n"

#. module: account_invoice_constraint_chronology
#: model:ir.model.fields,field_description:account_invoice_constraint_chronology.field_account_journal__check_chronology
msgid "Check Chronology"
msgstr "Provjeri kronologiju"

#. module: account_invoice_constraint_chronology
#. odoo-python
#: code:addons/account_invoice_constraint_chronology/model/account_move.py:0
#, python-format
msgid ""
"Chronology conflict: A conflicting draft invoice dated before {date_invoice} "
"exists, please validate it first."
msgstr ""
"Kronološka greška: Postoji problematični račun u nacrtu datiran prije "
"{date_invoice}, molim prvo njega potvrdite."

#. module: account_invoice_constraint_chronology
#. odoo-python
#: code:addons/account_invoice_constraint_chronology/model/account_move.py:0
#, python-format
msgid ""
"Chronology conflict: A conflicting validated invoice dated after "
"{date_invoice} exists."
msgstr ""
"Kronološka greška: Postoji potvrđeni račun sa datumom nakon {date_invoice}."

#. module: account_invoice_constraint_chronology
#. odoo-python
#: code:addons/account_invoice_constraint_chronology/model/account_move.py:0
#, python-format
msgid ""
"Chronology conflict: An invoice with a higher number {highest_name} dated "
"before {date_invoice} exists."
msgstr ""
"Kronološka greška: Račun sa većim brojem {highest_name} i datumom prije "
"{date_invoice} postoji."

#. module: account_invoice_constraint_chronology
#. odoo-python
#: code:addons/account_invoice_constraint_chronology/model/account_move.py:0
#, python-format
msgid ""
"Chronology conflict: Invoice {name} cannot be {time} invoice {inv_name}."
msgstr ""

#. module: account_invoice_constraint_chronology
#: model:ir.model,name:account_invoice_constraint_chronology.model_account_journal
msgid "Journal"
msgstr "Temeljnica"

#. module: account_invoice_constraint_chronology
#: model:ir.model,name:account_invoice_constraint_chronology.model_account_move
msgid "Journal Entry"
msgstr "Stavka dnevnika"

#, python-format
#~ msgid ""
#~ "Chronology Error. Please confirm older draft invoices before "
#~ "{date_invoice} and try again."
#~ msgstr ""
#~ "Greška kronologije: Molimo potvrdite starije račune prije {date_invoice} "
#~ "i pokušajte ponovo."

#, python-format
#~ msgid ""
#~ "Chronology Error. There exist at least one invoice with a later date to "
#~ "{date_invoice}."
#~ msgstr ""
#~ "Kronološka greška. Postoji najmanje jedan račun sa datum iza "
#~ "{date_invoice}."

#~ msgid "Invoice"
#~ msgstr "Račun"
